# ESRN Base Configuration

project:
  name: "ESRN"
  version: "0.1.0"
  author: "Zongq1"

data:
  dataset: "raven"
  batch_size: 32
  num_workers: 4
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

model:
  encoder:
    type: "vqvae"
    vocab_size: 512
    embed_dim: 64
    num_layers: 4
  
  rule_learner:
    num_rules: 64
    rule_dim: 128
    attention_heads: 8
  
  reasoning:
    max_steps: 5
    adaptive: true
  
  decoder:
    hidden_dim: 256
    num_classes: 8

training:
  optimizer: "adamw"
  learning_rate: 1.0e-4
  weight_decay: 0.01
  max_epochs: 100
  early_stopping_patience: 10
  
  scheduler:
    type: "cosine"
    warmup_epochs: 5

logging:
  log_every_n_steps: 50
  val_check_interval: 1.0
  save_top_k: 3
  
  wandb:
    project: "esrn"
    entity: null

system:
  seed: 42
  precision: 16
  accelerator: "gpu"
  devices: 1